// import js wrapper generated by wasm-bindgen
import { greet, default as init } from "hello-wasm";

// copy wasm to build dir
import hello from  "file-loader!hello-wasm/hello_wasm_bg.wasm";

// fetch and init module
init(hello)
  .then(res => console.log("greeting:", greet()))
  .catch(err => console.log(err));

const App = () => (<h1>Hello, World!</h1>);
export default App;
